tecdoc/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from tecdoc.views.cartype import CarTypeView, CarModelView 
from tecdoc.views.groups import GroupView
from tecdoc.views.manufacturer import ManufacturerList, ManufacturerView
from tecdoc.views.parts import PartView
from tecdoc.views.suppliers import SupplierList, SupplierView

urlpatterns = patterns("tecdoc.views",
    url(r'^manufacturers/$', ManufacturerList.as_view(),
        name='tecdoc-manufacturers'),
    url(r'^manufacturer/(?P<mnf_id>\d+)/$', ManufacturerView.as_view(),
        name='tecdoc-manufacturer'),
    url(r'^models/(?P<model_id>\d+)/$', CarModelView.as_view(),
        name='tecdoc-models'),

    url(r'^suppliers/$', SupplierList.as_view(),
        name='suppliers'),
    url(r'^suppliers/(?P<supplier_id>\d+)/$', SupplierView.as_view(),
        name='supplier'),

    url(r'^car_types/(?P<car_type_id>\d+)/$', CarTypeView.as_view(),
        name='car_type'),

    url(r'^categories/$', 'category.category_tree',
        name='category_tree'),
    url(r'^categories/(?P<parent>\d+)/$$', 'category.category_tree',
        name='category_tree'),

    url(r'^cartypes/(?P<type_id>\d+)/category/$',
        'category.category_tree_by_type',
        name='caregory_tree_by_type'),
    url(r'^cartypes/(?P<type_id>\d+)/category/(?P<parent>\d+)$',
        'category.category_tree_by_type',
        name='caregory_tree_by_type'),

    url(r'^groups/(?P<group_id>\d+)/$',
        GroupView.as_view(),
        name='group'),

    url(r'^parts/(?P<part_id>\d+)/$',
        PartView.as_view(),
        name='part'),
)

tecdoc/models/car.py
# -*- coding: utf-8 -

from django.core.cache import cache
from django.db import models

from tecdoc.conf import TecdocConf as tdsettings
from tecdoc.models.base import (TecdocModel, TecdocManager,
                                TecdocManagerWithDes)


class CarModelManager(TecdocManagerWithDes):

    def get_query_set(self, *args, **kwargs):
        return (super(CarModelManager, self).get_query_set(*args, **kwargs)
                                            .select_related('manufacturer',
                                                            'designation__description')
                                            .distinct()
               )

    def get_models(self, manufacturer, date_min=None, date_max=None,
                   search_text=None):

        query = self.filter(manufacturer=manufacturer)

        if date_min:
             # TODO
             pass

        if date_max:
             pass

        if search_text:
             query.filter(designation__description__text__icontains=search_text)

        return query


class CarModel(TecdocModel):
    YESNO = (('0', u'Нет'),
             ('1', u'Да'),
            )

    id = models.AutoField(u'Ид', primary_key=True,
                          db_column='MOD_ID')
    production_start = models.IntegerField(u'Начало производства',
                                        db_column='MOD_PCON_START')
    production_end = models.IntegerField(u'Конец производства',
                                      db_column='MOD_PCON_END')

    manufacturer = models.ForeignKey('tecdoc.Manufacturer',
                                     verbose_name=u'Производитель',
                                     db_column='MOD_MFA_ID')

    designation = models.ForeignKey('tecdoc.CountryDesignation',
                                    verbose_name=u'Обозначение',
                                    db_column='MOD_CDS_ID')

    for_car = models.SmallIntegerField(u'Для легковых',
                                       db_column='MOD_PC',
                                       choices=YESNO,
                                       blank=True, null=True)

    for_truck = models.SmallIntegerField(u'Для грузовых',
                                         db_column='MOD_CV',
                                         choices=YESNO,
                                         blank=True, null=True)

    objects = CarModelManager()

    def __unicode__(self):
        return u'%s %s (%s-%s)' % (self.manufacturer,
                                   self.designation,
                                   self.production_start, self.production_end or u'н.д.')

    class Meta(TecdocModel.Meta):
        db_table = tdsettings.DB_PREFIX + 'MODELS'


class EngineManager(TecdocManager):
    def get_query_set(self, *args, **kwargs):
        return (super(EngineManager, self).get_query_set(*args, **kwargs)
                                          .filter(fuel_des__lang=tdsettings.LANG_ID)
                                          .select_related('manufacturer',
                                                          'fuel_des__description')
               )


class Engine(TecdocModel):
    id = models.AutoField(u'Ид', primary_key=True,
                          db_column='ENG_ID')

    manufacturer = models.ForeignKey('tecdoc.Manufacturer',
                                     verbose_name=u'Производитель',
                                     db_column='ENG_MFA_ID')

    code = models.CharField(u'Код', max_length=180, db_column='ENG_CODE')

    production_start = models.IntegerField(u'Начало производства',
                                        db_column='ENG_PCON_START')
    production_end = models.IntegerField(u'Конец производства',
                                      db_column='ENG_PCON_END')

    power_kw_from = models.IntegerField(u'Мощность двигателя (кВт): ОТ',
                                        db_column='ENG_KW_FROM',
                                        blank=True, null=True)
    power_kw_upto = models.IntegerField(u'Мощность двигателя (кВт): До',
                                        db_column='ENG_KW_UPTO',
                                        blank=True, null=True)
    power_hp_from = models.IntegerField(u'Мощность двигателя (л.с.): ОТ',
                                        db_column='ENG_HP_FROM',
                                        blank=True, null=True)
    power_hp_upto = models.IntegerField(u'Мощность двигателя (л.с.): До',
                                        db_column='ENG_HP_UPTO',
                                        blank=True, null=True)

    fuel_des = models.ForeignKey('tecdoc.Designation',
                                 verbose_name=u'Кузов',
                                 db_column='ENG_KV_FUEL_TYPE_DES_ID',
                                 related_name='+'
                                 )

    objects = EngineManager()

    class Meta(TecdocModel.Meta):
        db_table = tdsettings.DB_PREFIX + 'ENGINES'


class CarTypeManager(TecdocManagerWithDes):

    def get_query_set(self, *args, **kwargs):
        return (super(CarTypeManager, self).get_query_set(*args, **kwargs)
                                           .filter(model__designation__lang=tdsettings.LANG_ID,
                                                   full_designation__lang=tdsettings.LANG_ID,
                                                   drive_des__lang=tdsettings.LANG_ID,
                                                   body_des__lang=tdsettings.LANG_ID,
                                                   designation__description__text__isnull=False)
                                           .select_related('model__manufacturer',
                                                           'model__designation__description',
                                                           'full_designation__description',
                                                           'designation__description',
                                                           'drive_des__description',
                                                           'body_des__description')
                                           .prefetch_related('engines')
               )


class CarType(TecdocModel):
    id = models.AutoField(u'Ид', primary_key=True,
                          db_column='TYP_ID')

    designation = models.ForeignKey('tecdoc.CountryDesignation',
                                    verbose_name=u'Обозначение',
                                    db_column='TYP_CDS_ID')

    full_designation = models.ForeignKey('tecdoc.CountryDesignation',
                                         verbose_name=u'Полное обозначение',
                                         db_column='TYP_MMT_CDS_ID',
                                         related_name='+'
                                        )

    model = models.ForeignKey(CarModel,
                              verbose_name=u'Модель',
                              db_column='TYP_MOD_ID',
                              related_name='cartypes')

    sorting = models.IntegerField(u'Порядок', db_column='TYP_SORT')

    production_start = models.IntegerField(u'Начало производства',
                                        db_column='TYP_PCON_START')
    production_end = models.IntegerField(u'Конец производства',
                                      db_column='TYP_PCON_END')

    engines = models.ManyToManyField(Engine, verbose_name=u'Двигатели',
                                     through='tecdoc.CarTypeEngine',
                                     related_name='cartypes')
    eng_volume = models.IntegerField(u'Объём двигателя (куб.см)',
                                     db_column='TYP_CCM',
                                     blank=True, null=True)
    cylinders = models.IntegerField(u'Количество цилиндров',
                                    db_column='TYP_CYLINDERS',
                                    blank=True, null=True)
    power_kw_from = models.IntegerField(u'Мощность двигателя (кВт): ОТ',
                                        db_column='TYP_KW_FROM',
                                        blank=True, null=True)
    power_kw_upto = models.IntegerField(u'Мощность двигателя (кВт): До',
                                        db_column='TYP_KW_UPTO',
                                        blank=True, null=True)
    power_hp_from = models.IntegerField(u'Мощность двигателя (л.с.): ОТ',
                                        db_column='TYP_HP_FROM',
                                        blank=True, null=True)
    power_hp_upto = models.IntegerField(u'Мощность двигателя (л.с.): До',
                                        db_column='TYP_HP_UPTO',
                                        blank=True, null=True)

    engine_des = models.ForeignKey('tecdoc.Designation',
                                   verbose_name=u'Двигатель',
                                   db_column='TYP_KV_ENGINE_DES_ID',
                                   related_name='+'
                                   )
    body_des = models.ForeignKey('tecdoc.Designation',
                                 verbose_name=u'Кузов',
                                 db_column='TYP_KV_BODY_DES_ID',
                                 related_name='+'
                                 )
    fuel_des = models.ForeignKey('tecdoc.Designation',
                                 verbose_name=u'Кузов',
                                 db_column='TYP_KV_FUEL_DES_ID',
                                 related_name='+'
                                 )

    drive_des = models.ForeignKey('tecdoc.Designation',
                                 verbose_name=u'Привод',
                                 db_column='TYP_KV_DRIVE_DES_ID',
                                 related_name='+'
                                 )

    objects = CarTypeManager()

    class Meta(TecdocModel.Meta):
        db_table = tdsettings.DB_PREFIX + 'TYPES'
        ordering = ['sorting', 'production_start']

tecdoc/models/supplier.py
# -*- coding: utf-8 -

from django.db import models
from django.db.models.base import ModelBase

from tecdoc.conf import TecdocConf as tdsettings
from tecdoc.models.base import (TecdocModel, TecdocManager,
                                TecdocManagerWithDes)
from tecdoc.models.common import Brand


class Supplier(TecdocModel):
    id = models.AutoField(u'Ид', primary_key=True,
                          db_column='SUP_ID')

    title = models.CharField(u'Название', max_length=60,
                             db_column='SUP_BRAND',
                             blank=True, null=True)

    class Meta(TecdocModel.Meta):
        db_table = tdsettings.DB_PREFIX + 'SUPPLIERS'
        verbose_name = u'Производитель запчастей'
        verbose_name_plural = u'Производители запчастей'

    __unicode__ = Brand.__unicode__.im_func

    def get_country(self):
        return self.addresses.filter(type=1,
                                     country_flag=0).get().country_postal


class SupplierLogo(TecdocModel):
    id = models.AutoField(u'Ид', primary_key=True,
                          db_column='SLO_ID')

    supplier = models.ForeignKey('tecdoc.Supplier',
                                 verbose_name=u'Поставщик',
                                 db_column='SLO_SUP_ID')

    language = models.ForeignKey('tecdoc.Language',
                                 verbose_name=u'Язык',
                                 db_column='SLO_LNG_ID')

    class Meta(TecdocModel.Meta):
        db_table = tdsettings.DB_PREFIX + 'SUPPLIER_LOGOS'


class SupplierAddress(TecdocModel):
    # XXX not a primary key
    supplier = models.ForeignKey('tecdoc.Supplier', primary_key=True,
                                 verbose_name=u'Поставщик',
                                 db_column='SAD_SUP_ID',
                                 related_name='addresses')

    type = models.IntegerField(u'Тип',
                               db_column='SAD_TYPE_OF_ADDRESS')

    # needed with value 0
    country_flag = models.IntegerField(u'Страна',
                                       db_column='SAD_COU_ID')

    country_postal = models.ForeignKey('tecdoc.Country',
                                       verbose_name=u'Почтовый адресс. Страна',
                                       db_column='SAD_COU_ID_POSTAL',
                                       related_name="addresses")

    class Meta(TecdocModel.Meta):
        db_table = tdsettings.DB_PREFIX + 'SUPPLIER_ADDRESSES'

tecdoc/views/cartype.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from tecdoc.models import CarModel, CarType


class CarTypeView(DetailView):
    model = CarType
    template_name = 'tecdoc/cartype.html'
    pk_url_kwarg = 'car_type_id'


class CarModelView(DetailView):
    model = CarModel

    template_name = 'tecdoc/cartypes.html'
    pk_url_kwarg = 'model_id'

tecdoc/views/groups.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView

from tecdoc.models import Group


class GroupView(DetailView):
    model = Group
    pk_url_kwarg = 'group_id'

    template_name = 'tecdoc/group.html'

tecdoc/views/manufacturer.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from tecdoc.models import Manufacturer


class ManufacturerList(ListView):
    queryset = Manufacturer.objects.filter(carmodel__gt=0).distinct()

    template_name = 'tecdoc/manufacturers.html'


class ManufacturerView(DetailView):
    model = Manufacturer
    pk_url_kwarg = 'mnf_id'

    template_name = 'tecdoc/manufacturer.html'

tecdoc/views/parts.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView
from django.template.response import TemplateResponse

from tecdoc.models import Part


class PartView(DetailView):
    model = Part
    pk_url_kwarg = 'part_id'

    template_name = 'tecdoc/part.html'


def search_view(request, query):
    form = SearchForm({'query': query})
    if form.is_valid():
        parts = Part.objects.lookup(query=form.cleaned_data['query'])
    else:
        parts = None
        messages.add_message()

    return TemplateResponse(request, 'tecdoc/search_part.html',
                            {'form': form,
                             'parts': parts})

tecdoc/views/suppliers.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from tecdoc.models import Supplier


class SupplierList(ListView):
    model = Supplier
   
    template_name = 'tecdoc/suppliers.html'


class SupplierView(DetailView):
    model = Supplier

    pk_url_kwarg = 'supplier_id'

    template_name = 'tecdoc/supplier.html'

tecdoc/templates/tecdoc/base.html
{% extends 'base.html' %}

tecdoc/templates/tecdoc/cartype.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}
{% load pagination_tags %}

{% block content %}
<h1>Модификация {{ object }}</h1>

<h2>Категории</h2>
<ul>
{% autopaginate object.list_categories %}
{% for cat in page_obj %}
  <li><a href="{% url 'category_tree' cat.id %}">{{cat}}</a></li>
{% endfor %}
</ul>
{% paginate %}

<h2>Запчасти</h2>
<ul>
{% autopaginate object.parts.all %}
{% for part in page_obj %}
  <li><a href="{% url 'part' part.id %}">{{part}}</a></li>
{% endfor %}
</ul>
{% paginate %}
{% endblock %}

tecdoc/templates/tecdoc/cartypes.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}
{% load pagination_tags %}

{% block content %}
<h1>Модель {{ object }}</h1>

<h2>Модификации ({{object.cartypes.count}})</h2>
<ul>
{% autopaginate object.cartypes.all %}
{% for car_type in page_obj %}
  <li><a href="{% url 'car_type' car_type.id %}">{{car_type}}</a></li>
{% endfor %}
</ul>
{% paginate %}
{% endblock %}

tecdoc/templates/tecdoc/categories.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}

{% block navigation %}
<ul>
{% if cat.id %}
  <li><a href="{% url 'category_tree' %}">Корень</a></li>
{% endif %}
{% for parent in cat.get_ancestors %}
  <li><a href="{% url 'category_tree' parent.id %}">{{ parent }}</a></li>
{% endfor %}
</ul>

<h1>{{cat.designation}}</h1>
<ul>
{% for child in cat.get_children %}
  <li><a href="{% url 'category_tree' child.id %}">{{child.designation}}</a></li>
{% endfor %}
</ul>
{% endblock %}

{% block content %}

<h1>{{cat.designation}}</h1>

<div class="parts">
{% load pagination_tags %}
{% autopaginate cat.get_groups %}
{% paginate %}
<h2>Универсальные группы ({{page_obj.paginator.count}})</h2>
<ul>
{% for group in page_obj %}
<li><a href="{% url 'group' group.id %}">{{ group }}</a></li>
{% endfor %}
</ul>
{% paginate %}

{% autopaginate cat.get_parts %}
<h2>Запчасти (всего {{ page_obj.paginator.count }})</h2>
{% paginate %}
<ul>
{% for part in page_obj %}
<li><a href="{% url 'part' part.id %}">{{ part }}</a>
  {% for image in part.images.all %}
    <img src="{{image.url}}" />
  {% endfor %}
</li>
{% endfor %}
</ul>
{% paginate %}
</div>
{% endblock %}

tecdoc/templates/tecdoc/group.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}

{% block content %}
<div class="part">
{% load pagination_tags %}
<h1>Универсальная запчасть {{ object }}</h1>

{% load pagination_tags %}
{% autopaginate object.parts.distinct.all %}
<h2>Запчасти ({{page_obj.paginator.count}})</h2>
<ul>
{% for part in page_obj %}
<li><a href="{% url 'part' part.id %}">{{ part }}</a></li>
{% endfor %}
</ul>
{% paginate %}

<h2>Категории ({{object.sections.count}})</h2>
<ul>
{% for category in object.sections.all %}
<li><a href="{% url 'category_tree' category.id %}">{{ category }}</a></li>
{% endfor %}
</ul>

</div>
{% endblock %}

tecdoc/templates/tecdoc/manufacturer.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}

{% block content %}
<h1>Производитель {{object}}</h1>
<p>Всего моделей: {{object.carmodel_set.count}}</p>

{% load pagination_tags %}
{% autopaginate object.carmodel_set.all %}
<ul>
{% for model in page_obj %}
  <li><a href="{% url 'tecdoc-models' model.id %}">{{model}}</a></li>
{% endfor %}
</ul>
{% paginate %}
{% endblock %}

tecdoc/templates/tecdoc/manufacturers.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}

{% block content %}
<h1>Производители (Всего {{ object_list.count }})</h1>
{% load pagination_tags %}
{% autopaginate object_list %}
<ul>
{% for mnf in page_obj %}
  <li><a href="{% url 'tecdoc-manufacturer' mnf.id %}">{{mnf.title}}</a></li>
{% endfor %}
</ul>
{% paginate %}
{% endblock %}

tecdoc/templates/tecdoc/part.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}

{% block content %}
<div class="part">
{% load pagination_tags %}
<h2>{{ part }}</h2>
<ul>
  {% for image in part.images.all %}
    <li><img src="{{image.url}}" /></li>
  {% endfor %}
</ul>


<h3>Входит в группы</h3>
<ul>
{% for group in part.groups.distinct.all %}
<li><a href="{% url 'group' group.id %}">{{ group }}</a></li>
{% endfor %}
</ul>

<h3>Оговорки</h3>
<ul>
{% for criteria in part.criteries.all %}
<li>{{ criteria }}</li>
{% endfor %}
</ul>

<h3>Модели</h3>
<ul>
{% load pagination_tags %}
{% autopaginate part.list_car_types.all %}
{% for car_type in page_obj %}
<li><a href="{% url 'car_type' car_type.id %}">{{ car_type }}</a></li>
{% endfor %}
</ul>

</div>
{% endblock %}

tecdoc/templates/tecdoc/supplier.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}

{% block content %}
<h1>Производитель запчастей {{ object }}</h1>

{% endblock %}

tecdoc/templates/tecdoc/suppliers.html
{% extends 'tecdoc/base.html'%}

{% load url from future %}

{% block content %}
<h1>Производители запчастей (Всего {{ object_list.count }})</h1>
<ul>
{% load pagination_tags %}
{% autopaginate object_list %}
{% for supplier in page_obj %}
  <li><a href="{% url 'supplier' supplier.id %}">{{supplier}}</a></li>
{% endfor %}
</ul>
{% paginate %}
{% endblock %}